name: Development

on:
  push:
    branches:
      - '**'
    branches_ignore:
      - main
  pull_request:
    branches:
      - '**'
    branches_ignore:
      - main

jobs:
  Build:
    name: Build and Run Unit-Tests with .Net Core SDK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v1
    - name: Install .Net Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore
      run: dotnet restore ./ServiceRequestManagement.sln
    - name: Build
      run: dotnet build ./ServiceRequestManagement.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./tests/ServiceRequestManagement.UnitTests/ServiceRequestManagement.UnitTests.csproj --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=\"[*]ServiceRequestManagement.Infrastructure.*,[*]*Startup,[*]*Program,[*]ServiceRequestManagement.API.Controllers.*,[*]ServiceRequestManagement.API.Application.Behaviors.*,[*]*ServiceCollectionExtensions,[*]*WebHostExtensions\"